print("##############################") 
print("#                            #") 
print("#  Arif fatahillah Permana   #") 
print("#       2410817310016        #") 
print("#                            #") 
print("##############################")
